# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Mine'), ('S', 'Spouse'), ('D', 'Dependents')], max_length=20)),
                ('doc_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('job_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ten95B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten95C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten98EStudentLoanInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten98TTuitionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99DIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_dividends', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99INT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(blank=True, max_length=30)),
                ('interest_income', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99MISC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='W2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='w2')),
                ('order', models.IntegerField(default=0)),
                ('auto_start', models.BooleanField(default=False)),
                ('ssn', models.CharField(blank=True, max_length=50)),
                ('ein', models.CharField(blank=True, max_length=50)),
                ('wage', models.CharField(blank=True, max_length=20)),
                ('federal_income', models.CharField(blank=True, max_length=20)),
                ('social_security_wages', models.CharField(blank=True, max_length=30)),
                ('social_security_tax', models.CharField(blank=True, max_length=30)),
                ('medicare_wages', models.CharField(blank=True, max_length=30)),
                ('medicare_tax', models.CharField(blank=True, max_length=30)),
                ('social_security_tips', models.CharField(blank=True, max_length=30)),
                ('allocated_tips', models.CharField(blank=True, max_length=30)),
                ('control_number', models.CharField(blank=True, max_length=30)),
                ('dependent_care_benefits', models.CharField(blank=True, max_length=30)),
                ('employee_first_name', models.CharField(blank=True, max_length=30)),
                ('employee_last_name', models.CharField(blank=True, max_length=30)),
                ('employee_zip_code', models.CharField(blank=True, max_length=30)),
                ('employee_state', models.CharField(blank=True, max_length=30)),
                ('employer_name', models.CharField(blank=True, max_length=150)),
                ('employer_city', models.CharField(blank=True, max_length=150)),
                ('employer_state', models.CharField(blank=True, max_length=150)),
                ('employer_street', models.CharField(blank=True, max_length=150)),
                ('employer_zip', models.CharField(blank=True, max_length=150)),
                ('employer_state2', models.CharField(blank=True, max_length=150)),
                ('employer_state_id', models.CharField(blank=True, max_length=150)),
                ('non_qualified_plans', models.CharField(blank=True, max_length=30)),
                ('box12a', models.CharField(blank=True, max_length=30)),
                ('box12b', models.CharField(blank=True, max_length=30)),
                ('box12c', models.CharField(blank=True, max_length=30)),
                ('box12d', models.CharField(blank=True, max_length=30)),
                ('box13_se', models.CharField(blank=True, max_length=30)),
                ('box13_rp', models.CharField(blank=True, max_length=30)),
                ('box13_tpsp', models.CharField(blank=True, max_length=30)),
                ('box14_type', models.CharField(blank=True, max_length=30)),
                ('bx_14_amount', models.CharField(blank=True, max_length=30)),
                ('state_wages', models.CharField(blank=True, max_length=30)),
                ('state_tax', models.CharField(blank=True, max_length=30)),
                ('locality_name', models.CharField(blank=True, max_length=30)),
                ('local_wages', models.CharField(blank=True, max_length=30)),
                ('local_tax', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
    ]
