# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoinput.DividendIncome')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoinput.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='W2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='w2')),
                ('auto_start', models.BooleanField(default=False)),
                ('ssn', models.CharField(blank=True, max_length=50)),
                ('ein', models.CharField(blank=True, max_length=50)),
                ('wage', models.CharField(blank=True, max_length=20)),
                ('federal_income', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('ss_wages', models.CharField(blank=True, max_length=30)),
                ('ss_tax', models.CharField(blank=True, max_length=30)),
                ('medicare_wages', models.CharField(blank=True, max_length=30)),
                ('medicare_tax', models.CharField(blank=True, max_length=30)),
                ('ss_tips', models.CharField(blank=True, max_length=30)),
                ('all_tips', models.CharField(blank=True, max_length=30)),
                ('control_number', models.CharField(blank=True, max_length=30)),
                ('dp_care_benefits', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('nq_plans', models.CharField(blank=True, max_length=30)),
                ('box12a', models.CharField(blank=True, max_length=30)),
                ('box12b', models.CharField(blank=True, max_length=30)),
                ('box12c', models.CharField(blank=True, max_length=30)),
                ('box12d', models.CharField(blank=True, max_length=30)),
                ('st_employee', models.CharField(blank=True, max_length=30)),
                ('retire_plan', models.CharField(blank=True, max_length=30)),
                ('tp_sick_pay', models.CharField(blank=True, max_length=30)),
                ('other', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('st_id_number', models.CharField(blank=True, max_length=30)),
                ('st_wages', models.CharField(blank=True, max_length=30)),
                ('st_tax', models.CharField(blank=True, max_length=30)),
                ('locality_name', models.CharField(blank=True, max_length=30)),
                ('lc_wages', models.CharField(blank=True, max_length=30)),
                ('lc_tax', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten99',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten99'),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='w2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoinput.W2'),
        ),
    ]
