# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('autoinput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedoc',
            name='tax_payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.TaxPayerProfile'),
        ),
        migrations.AddField(
            model_name='engine',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autoinput.Car'),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Reporter'),
        ),
    ]
