# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('job_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
