# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0002_auto_20171021_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='w2',
            name='allocated_tips',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box12a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box12b',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box12c',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box12d',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box13_rp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box13_se',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box13_tpsp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='box14_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='bx_14_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='control_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='dependent_care_benefits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employee_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employee_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employee_zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_state2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_state_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='employer_zip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='federal_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='local_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='local_wages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='locality_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='medicare_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='medicare_wages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='non_qualified_plans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='social_security_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='social_security_tips',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='social_security_wages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='state_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='state_wages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='w2',
            name='wage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
