# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(),
        ),
    ]
