# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0003_auto_20171021_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='w2',
            old_name='bx_14_amount',
            new_name='box14_amount',
        ),
    ]
