# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0003_auto_20171012_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedoc',
            name='doc_order',
            field=models.IntegerField(default=0),
        ),
    ]
