# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0003_auto_20171009_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ten95B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ten95C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ten98',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgage_interest', models.CharField(blank=True, max_length=30)),
                ('refund', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ten99DIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_dividends', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ten99INT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(blank=True, max_length=30)),
                ('interest_income', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='dividend_income',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten99',
        ),
        migrations.AlterField(
            model_name='sourcedoc',
            name='w2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.W2'),
        ),
        migrations.DeleteModel(
            name='Ten99',
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten95b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten95B'),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten95c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten95C'),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten98',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten98'),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten99div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten99DIV'),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='ten99int',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.Ten99INT'),
        ),
    ]
