# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0004_auto_20171022_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2',
            name='cut_end_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='w2',
            name='cut_start_points',
            field=models.TextField(blank=True),
        ),
    ]
