# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0005_auto_20171022_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2',
            name='employee_city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
