# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0005_dividendincome_source_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ten98EStudentLoanInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten98TTuitionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30)),
                ('ssn', models.CharField(blank=True, max_length=30)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99MISC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Ten99Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc')),
            ],
        ),
        migrations.RenameModel(
            old_name='DividendIncome',
            new_name='ChildCare',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='ten98',
            name='source_doc',
        ),
        migrations.DeleteModel(
            name='Ten98',
        ),
    ]
