# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0006_w2_employee_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ten99int',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='ten99int',
            name='name',
        ),
        migrations.AddField(
            model_name='ten99int',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='bond_premium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='bond_premium_tax_exempt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='city_check',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='doc_order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='early_withdrawal_penalty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='fatca_filling',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='federal_income_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='foreign_country_us_possession',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='foreign_tax_paid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ten99int'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ten99int',
            name='interest_us_saving_bonds',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='investment_expenses',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='market_discount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='payer_federal_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='payer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='payer_rtn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='recipient_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='recipient_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='recipient_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='specified_private_bond',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='state_check',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='state_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='state_recheck',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='state_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='street_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='tax_exempt_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='tax_exempt_tax_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='zip_code_check',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ten99int',
            name='interest_income',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
