# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171010_1556'),
        ('autoinput', '0006_car_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten95b',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten95c',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten98',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten99div',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='ten99int',
        ),
        migrations.RemoveField(
            model_name='sourcedoc',
            name='w2',
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mine'), ('S', 'Spouse'), ('C', 'Child')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sourcedoc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.TaxPayerProfile'),
        ),
        migrations.AddField(
            model_name='ten95b',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
        migrations.AddField(
            model_name='ten95c',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
        migrations.AddField(
            model_name='ten98',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
        migrations.AddField(
            model_name='ten99div',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
        migrations.AddField(
            model_name='w2',
            name='source_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoinput.SourceDoc'),
        ),
    ]
