# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0007_auto_20171129_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ten99int',
            name='doc_order',
        ),
        migrations.AddField(
            model_name='ten99int',
            name='cut_end_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ten99int',
            name='cut_start_points',
            field=models.TextField(blank=True),
        ),
    ]
