# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoinput', '0009_auto_20171205_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ten99div',
            old_name='state_id',
            new_name='state_in',
        ),
    ]
