# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Enter a unique name for the task', max_length=128)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
