# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxorganizer',
            name='personal_info',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
