# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import functions.randomfilename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to=functions.randomfilename.RandomFileName('cars/volvo'))),
            ],
        ),
    ]
