from django.db import models

__all__ = ('W2', )


class W2(models.Model):
    ssn = models.CharField(max_length=50)
    ein = models.CharField(max_length=50)
    wage = models.CharField(max_length=20)
    federal_income = models.CharField(max_length=20)
    name = models.CharField(max_length=150)
    ss_wages = models.CharField(max_length=30)
    ss_tax = models.CharField(max_length=30)
    medicare_wages = models.CharField(max_length=30)
    medicare_tax = models.CharField(max_length=30)
    ss_tips = models.CharField(max_length=30)
    all_tips = models.CharField(max_length=30)
    control_number = models.CharField(max_length=30)
    dp_care_benefits = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    zip_code = models.CharField(max_length=30)
    nq_plans = models.CharField(max_length=30)
    box12a = models.CharField(max_length=30)
    box12b = models.CharField(max_length=30)
    box12c = models.CharField(max_length=30)
    box12d = models.CharField(max_length=30)
    st_employee = models.CharField(max_length=30)
    retire_plan = models.CharField(max_length=30)
    tp_sick_pay = models.CharField(max_length=30)
    other = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    st_id_number = models.CharField(max_length=30)
    st_wages = models.CharField(max_length=30)
    st_tax = models.CharField(max_length=30)
    locality_name = models.CharField(max_length=30)
    lc_wages = models.CharField(max_length=30)
    lc_tax = models.CharField(max_length=30)