# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayerprofile',
            name='children_source_doc',
        ),
        migrations.RemoveField(
            model_name='taxpayerprofile',
            name='my_source_doc',
        ),
        migrations.RemoveField(
            model_name='taxpayerprofile',
            name='spouse_source_doc',
        ),
        migrations.AddField(
            model_name='taxpractitionerprofile',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile/practitioner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxpayerprofile',
            name='img',
            field=models.ImageField(upload_to='profile/payer'),
        ),
        migrations.AlterField(
            model_name='taxpayerprofile',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxorg.TaxOrganizer'),
        ),
    ]
