# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171010_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayerprofile',
            name='organizer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='taxorg.TaxOrganizer'),
        ),
    ]
