# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20171010_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayerprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/payer'),
        ),
        migrations.AlterField(
            model_name='taxpayerprofile',
            name='organizer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxorg.TaxOrganizer'),
        ),
        migrations.AlterField(
            model_name='taxpractitionerprofile',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, through='member.Connection', to='member.TaxPayerProfile'),
        ),
        migrations.AlterField(
            model_name='taxpractitionerprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/practitioner'),
        ),
    ]
